### ISSUE TITLE
请问一下，pod里面使用oc的第三方，没看到楼主做桥接文件，如何实现的？

### ISSUE THREAD

**Issue by SamXZP** [spicyShrimp/U17#10]

**Comment by spicyShrimp** [comment]
import MJRefresh 类似这样就可以了

**Comment by SamXZP** [comment]
我不用桥接会报错的，你是特殊处理了么？

**Comment by spicyShrimp** [comment]
并不是没有桥接文件,而是cocoapods的处理
如果在cocoapods 里面不使用 use_frameworks!,则是通过static libraries 这个方式来管理pod的代码。这样就需要在app-Bridging-Header.h 文件里面去import相应的.h 文件。而如果使用了use_frameworks!,则cocoapods 使用了frameworks 来取代static libraries 方式,则只需要使用import MJRefresh就可以了

**Comment by SamXZP** [comment]
学到了，刚从oc换swift，你这个项目对我帮助很大。架构和我用oc写的方式也差不多，谢谢大神。
