### ISSUE TITLE
HandyJSON 出现Undefined symbols for architecture x86_64(真机测试为arm64)

### ISSUE THREAD

**Issue by zwg11** [spicyShrimp/U17#13]
Undefined symbols for architecture x86_64:
  "_swift_getTypeByMangledNameInContext", referenced from:
      HandyJSON.Metadata.Class._propertyDescriptionsAndStartPoint() -> ([HandyJSON.Property.Description], Swift.Int32?)? in Metadata.o
      HandyJSON.Metadata.Struct.propertyDescriptions() -> [HandyJSON.Property.Description]? in Metadata.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

不知道是这个类库本身不支持还是我的设置有问题

**Comment by 871263000** [comment]
我也有这个问题， 不知道谁解决了吗

**Comment by spicyShrimp** [comment]
你试试更新下,看看还有没有问题 已经更新了库了

**Comment by helloMrTom** [comment]
现在应该没有问题了
