### ISSUE TITLE
xocde 11.3.1 真机ios13.3.1 xsMax pod的第三方库调用不到

### ISSUE THREAD

**Issue by likeuu** [spicyShrimp/U17#16]
更新了POD库，模拟器调试没问题，真机调试，pod里的第三方库调用地方报错，获取不到值（nil），感觉像是第三方库没有加载。网上找了各种办法也没有解决，不知道怎么解决。
调用 IQKeyboardManager.shared.enable = true 就直接崩溃了，真机时第三方库里面的断点都不跑，模拟就都可以跑到。

**Comment by spicyShrimp** [comment]
已更新pod库
