### ISSUE TITLE
运行崩溃 dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire

### ISSUE THREAD

**Issue by linyiios** [spicyShrimp/U17#19]
运行的时候，报了这个错。
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /private/var/containers/Bundle/Application/735CEFA6-E999-4641-AD5B-090277C03602/U17.app/U17
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/735CEFA6-E999-4641-AD5B-090277C03602/U17.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/735CEFA6-E999-4641-AD5B-090277C03602/U17.app/Frameworks/Alamofire.framework/Alamofire'

在Alamofire 这里，找到了解答，楼主可以考虑把这个问题放在readme里面。蟹蟹٩('ω')و
https://github.com/Alamofire/Alamofire/issues/101

**Comment by spicyShrimp** [comment]
更新了SDK
