### ISSUE TITLE
发现一个潜在bug

### ISSUE THREAD

**Issue by xubillde** [spicyShrimp/U17#2]
非常感谢分享代码，方便学习

UBoutiqueListViewController.swift
104行，这个属性不应该强制解包吧
`
self?.bannerView.imagePaths = self?.galleryItems.map { $0.cover! } ?? []
`

测试
`
self?.gallertItems.append(GalleryItemModel(id: 1, linkType: 1, cover: nil, ext: [ExtModel(key:"1", val: "13")], title: "1", content: "12"))
 self?.bannerView.imagePaths = self?.galleryItems.map { guard let v = $0.cover else {return ""} ; return v } ?? []
`

**Comment by spicyShrimp** [comment]
已经添加了解包前的空值过滤  初时未作考虑 感谢你的关注
