### ISSUE TITLE
为何要用UMineHead

### ISSUE THREAD

**Issue by narakai** [spicyShrimp/U17#5]
不是很明白：tableView可以直接设置parallaxHeader.view为image，包一层UMineHead是否是多余的呢？

**Comment by spicyShrimp** [comment]
可以直接设置图片，但是如果是有更换图片的需求，是直接设置图片的image方便呢？还是重新设置parallaxHeader.view方便呢？如果头部不仅仅是一张图片，里面还有很多子控件呢？

**Comment by narakai** [comment]
ok 明白了 谢谢解答 ：）
